version: '3'

volumes:
  postgres_data:
    driver: local

services:

  postgres:
    image: postgres:14.4-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    ports:
      - "5436:5432"

  keycloak:
    image: sleighzy/keycloak:16.1.0-arm64
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      PROXY_ADDRESS_FORWARDING: 'true'
    ports:
      - "9090:8080"
    depends_on:
      - postgres

  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"