spring:
  cloud:
    gateway:
      routes:
        - id: openapi
          uri: http://localhost:8080
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs
        - id: keycloak-admin-client
          uri: lb://keycloak
          predicates:
            - Path=/**
          filters:
            - RewritePath=/keycloak/(?<path>.*), /$\{path}
  application:
    name: api-gateway


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
