spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/task
    username: postgres
    password: admin


  jpa:
    database: POSTGRESQL
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      maxFileSize: 2000MB
      maxRequestSize: 2000MB

  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:9090/auth/realms/mini-project-2
          jwk-set-uri: ${spring.security.oauth2.resource-server.jwt.issuer-uri}/protocol/openid-connect/certs

server:
  port: 8089