#spring:
#  config:
#    import: optional:configserver:http://localhost:8888
#  profiles:
#    active: develop

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/auth/realms/mini-project-2
          jwk-set-uri: http://localhost:9090/auth/realms/mini-project-2/protocol/openid-connect/certs

  application:
    name: task-service
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 2003
    url: jdbc:postgresql://localhost:5432/task_database
  sql:
    init:
      platform: postgres

server:
  port: 9092
  servlet:
    context-path: /

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

openapi:
  service:
    title: task-service
    version: 1.0.0
    url: http://localhost:8080
springdoc:
  api-docs:
    path: /task-service/v3/api-docs
  swagger-ui:
    path: /task-service/swagger-ui.html