spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/auth/realms/mini-project-2
          jwk-set-uri: http://localhost:9090/auth/realms/mini-project-2/protocol/openid-connect/certs
  application:
    name: keycloak

server:
  port: 9091

keycloak:
  realm: mini-project-2
  resource: mini-project
  auth-server-url: http://localhost:9090/auth/ #docker container
  credentials:
    client-id: mini-project
    secret: lEEUi2nQpBG0XVzV8rtaEnlkcXApRrkF
    provider: secret

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
